### ISSUE TITLE
Recommendations from @jasonglazer

### ISSUE THREAD

**Issue by Myoldmopar** [Myoldmopar/EPLaunchLight#1]
# Still to do:
- [ ] Hmmm parametric files. Not sure why. I wonder if HVAC-Template files work? -- Umm, deferred because the CLI doesn't call the parametric preprocessor yet?? Right?
- [ ] I'll mess with the alignment of the whole body of the application. GTK box packing has lots of knobs to turn to get it just right.
- [ ] Store recently used files
# Things completed:
- [x] Add button to simulation complete/fail dialog to allow user to open run folder in Finder
- [X] Changing it to select IMFs is a great easy addition
- [X] Printing the version in the status bar is another great addition
- [X] Going to the CLI will clean up the output from the deprecated script stuff
- [X] OK, I can change the dialog to be an error message dialog for fatals
- [X] I can have it remember the last folder. It will be super easy within a single session, but I could keep a settings file somewhere to persist it between sessions. I think that persisting will wait in favor of fixing up these other things. -- Done for a single session
- [X] Store last used folder between sessions
- [X] Persist separate last-folders for idf and epw
- [X] Allow adjustment of command line args to trigger ExpandObjects, etc. - Not exactly, I just use ReadVars and ExpandObjects each time just like the previous run script.  I _could_ reveal annual/design day but I don't think I will for now.
- [x] Internationalization? [get_text tips](http://www.wefearchange.org/2012/06/the-right-way-to-internationalize-your.html)
- [X] Clean up any strings in the code (dictionary keys, etc.)
  - [x] As for opening the files, what application should I open them with by default? I can certainly call a subprocess to open it in TextEdit or something, but people use different editors when they are editing the idfs manually.
- [X] I made the name up as somewhat of a joke, but whatever name we go with (EP-Launch-Lite-2?), I'll make sure it's consistent
# Things deferred:
- The buttons and such are directly from pygtk, so I'm not sure I'll easily get around that.
- I'll figure out an app icon and add it in there. (-- skipped because PyGTK + Mac doesn't work well)

**Comment by JasonGlazer** [comment]
@Myoldmopar I could not run the ddbe30c release:

9/19/16 10:18:24.326 AM EnergyPlusLaunchLight[384]  Traceback (most recent call last):
9/19/16 10:18:24.326 AM EnergyPlusLaunchLight[384]    File "/Applications/EnergyPlus-8-6-0/EnergyPlusLaunchLight-2.app/Contents/Resources/**boot**.py", line 351, in <module>
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]      _run()
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]    File "/Applications/EnergyPlus-8-6-0/EnergyPlusLaunchLight-2.app/Contents/Resources/__boot__.py", line 336, in _run
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]      exec(compile(source, path, 'exec'), globals(), globals())
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]    File "/Applications/EnergyPlus-8-6-0/EnergyPlusLaunchLight-2.app/Contents/Resources/EnergyPlusLaunchLight.py", line 14, in <module>
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]      this_settings = load_settings(this_settings_file_name)
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]    File "EPLaunchLight/Settings.pyc", line 20, in load_settings
9/19/16 10:18:24.327 AM EnergyPlusLaunchLight[384]  NameError: global name 'os' is not defined
9/19/16 10:18:24.425 AM EnergyPlusLaunchLight[384]  EnergyPlusLaunchLight Error
9/19/16 10:18:24.425 AM EnergyPlusLaunchLight[384]  2016-09-19 10:18:24.424 EnergyPlusLaunchLight[384:7113] EnergyPlusLaunchLight Error

I will try the most recent release next.

**Comment by Myoldmopar** [comment]
Awesome, thanks for trying it.  Yeah, that should be fixed in the latest one.  I was about to ask a friend with a fairly "raw" Mac image to try it as well.

**Comment by JasonGlazer** [comment]
Just tried 46dbc8d and it ran ok. Thanks for fixing so many of the issues I pointed out Friday. I like the language selection option. Why did you change the output approach to be the generic "eplus" files in the input file named directory? I find that more confusing. I think you are using the CLI, can you add the --output-prefix as the original file name?

**Comment by Myoldmopar** [comment]
Done: eef02e8

What about the output directory though?  I thought output-`Filename` would be nice, but I'm not sure.  I'm open to changing it.

**Comment by JasonGlazer** [comment]
I am not sure about GTK but with other GUI toolkits I have used, if you put the two choose buttons in a "frame" and the two text inputs in another "frame" and then put the two frames next to each other, I think the alignment stuff might work better.

**Comment by JasonGlazer** [comment]
I am ok with the output-filename approach also although I am used to them being in the same directory as the original. Mostly it when you open a bunch of files from different runs and the error files are all called eplusout.err in the text editor that it gets confusing.

**Comment by Myoldmopar** [comment]
Yeah, right now it's primarily row-based, with hbox-rows filling up a big vbox-column such that each row doesn't know anything about the alignment of pieces in the next row.  Changing it to a more column based layout would help those buttons line up perfectly, but would require enough change that I'm not going to worry about it for right now.  It's a totally doable thing for when there's a little more time.

**Comment by Myoldmopar** [comment]
> Mostly it when you open a bunch of files from different runs and the error files are all called eplusout.err in the text editor that it gets confusing.

OK, well with the filenames now like: `/path/to/idf/output-idfname/idfname.err`, the uncertainty of files should be gone.  I may have French done in a minute so that our French-Canadian friends can use this _wonderful_ tool :wink:.

**Comment by JasonGlazer** [comment]
Sounds good.

Now we need Chinese and Portuguese :-)

**Comment by Myoldmopar** [comment]
Did the parametric preprocessor ever get run by the batch files?  I can't find it in there.  Only in the specific RunParam.bat file.  Or maybe I'm missing something.  

If it should be added to the command line options, then I will open an issue to add it to E+ core so that it can be used by this tool.

**Comment by JasonGlazer** [comment]
I don't think it was ever supported by the CLI so it should by added.

**Comment by JasonGlazer** [comment]
Every imf file I try fails. Did you get any of them to work?

**Comment by Myoldmopar** [comment]
Hmm...macro.  OK, well `-m` wasn't set either on the CLI.  But I added that and it still fails because it can't find the supporting imf files.  Lemme check...

**Comment by JasonGlazer** [comment]
Also when you open an IDF file and press the "Edit Input File" button it works but not when you open an IMF file.

**Comment by Myoldmopar** [comment]
Yeah, that's just using the default application to open the file.  You likely have a default option to open idf files.  But imf probably not.  Once you set a default application for imf it should work.

As for imf, I can run AbsorptionChiller_Macro.imf, but I have to give it the `##fileprefix` to the supporting imf files.  Once I do that, it runs fine (with the -m CLI flag).

I'll push that change up.  I'll also update the text to alert users that they may want to try opening the imf from Finder first in order to set up a default application.

**Comment by JasonGlazer** [comment]
Another weirdness: the File and Language menus seem to open in the original place on the screen even if you have moved the EP-Launch-Lite window.

**Comment by Myoldmopar** [comment]
> Another weirdness: the File and Language menus seem to open in the original place on the screen even if you have moved the EP-Launch-Lite window.

Mine is fine there...that's an odd one.

**Comment by Myoldmopar** [comment]
Pushed a [new release](https://github.com/Myoldmopar/EPLaunchLight/releases/tag/v2.0-Alpha2).  Feel free to download if you are interested; it should really just be the EP-Macro and imf error fixes.

Thanks for the help in quickly testing this out.  I think it's quite close to being "done for 8.6"

**Comment by JasonGlazer** [comment]
I will test it.

Will you be able to "sign" the application so that it opens normally without right clicking it?

**Comment by Myoldmopar** [comment]
That's a great question.  Did we sign EP-Launch-Lite before?  Hmm..

**Comment by Myoldmopar** [comment]
The answer's going to be no on the signing...for now.  If dropping it into the installer package makes it difficult to use, I don't mind keeping it separate for right now.  I can change the Mac readme to include a link to download it and a brief instruction about right clicking to open it.

**Comment by JasonGlazer** [comment]
Put it in the installer, I think most MacOS users have dealt with unsigned apps. 

I think it will be helping a lot of Mac users!

**Comment by Myoldmopar** [comment]
Have you tried running it from /Applications?  I just dropped a new build inside the /Applications folder ... essentially installing it... and it didn't ask.  Maybe it's just already approved it on my machine.

**Comment by JasonGlazer** [comment]
It gave me the "downloaded from the internet" warning the first time but not after that.

**Comment by Myoldmopar** [comment]
OK, sounds reasonable for now.  Thanks!  I guess I'll work now to replace the older version in the installer.

**Comment by Myoldmopar** [comment]
@JasonGlazer I made the PR to put it in the installer over in NREL/EnergyPlus.  This repo will probably just die off.  Any further issues should be opened over there.
